### ISSUE TITLE
Broken links in the pull request's search result

### ISSUE THREAD

**Issue by DmitryGulin** [ostreifel/Pull-Request-Search#1]
When you try to navigate to the Pull Request search result item, it would use 'undefined' repo name regardless of actual repository name where Pull Request was executed. We do not have undefined leading anywhere, thus, TFS navigates to a broken link.

Looks like ${pr.repository.name} has undefined value in const url = `${uri}${project}/${team}/_git/${pr.repository.name}/pullrequest/${pr.pullRequestId}`; (PullRequestsView.tsx)

**Comment by ostreifel** [comment]
Is this for all pull requests in the repository? 
Is this only pull requests created during a certain time period for a that repository? 
Can you [post ](https://www.visualstudio.com/en-us/docs/integrate/api/git/pull-requests/pull-requests#get-a-list-of-pull-requests-in-the-repository) a sample post response containing a pull request that does not show a repository name from the network tab in chrome?
Is there anything that might make this repository unusual?
