### ISSUE TITLE
Provide filter for all merge request a person is "involved in"

### ISSUE THREAD

**Issue by woutervanvliet** [ostreifel/Pull-Request-Search#12]
It would be great to get a single view of all merge request I'm involved in, either because I created it or because I'm assigned to it. Currently it only seems possible to see either PRs I've created OR am assigned to as reviewer.

It would be even better it could filter on those I need to "action on", which I would define as any form of new activity since I've last done something with that PR.

**Comment by ostreifel** [comment]
Unfortunately the api's available to extensions would not be able to do something like that.
