### ISSUE TITLE
Add a "loading spinner" while searching

### ISSUE THREAD

**Issue by kenotron** [ostreifel/Pull-Request-Search#3]

**Comment by ostreifel** [comment]
Searches should be immediate. Can you give more information about the response times that you are seeing and what the dataset you searching? - number of pull requests / search criteria etc

**Comment by kenotron** [comment]
So, the UX is that the user makes a search and the extension makes an AJAX call to the API. It is generally fast, but there is a period of time (in terms of seconds) before response arrives. This is in a project with about 10-20 PRs actively - the response would be worse when searching completed PRs. 

Having a spinner to show that the page is doing something is generally a good way to let user know that "something is happening." I can't imagine it to be that difficult to do, FWIW.

**Comment by ostreifel** [comment]
Added loading message

1.9.1 - https://marketplace.visualstudio.com/items?itemName=ottostreifel.pull-request-search
