### ISSUE TITLE
TFS On-Prem broken links

### ISSUE THREAD

**Issue by gregor4005** [ostreifel/Pull-Request-Search#6]
Links to PRs are broken in TFS On-Prem installation.
They are `https://SERVER/tfs/DefaultCollection/Project/Project%20Team/_git/undefined/pullrequest/3391` instead of `https://SERVER/tfs/DefaultCollection/Project/_git/SomeRepo/pullrequest/3391`
Note: Installed TFS version is 2015 U2 and extension version is 1.9.8

**Comment by gregor4005** [comment]
This issue seems identical with #1

**Comment by ostreifel** [comment]
Updated v1.9.12
