### ISSUE TITLE
TFS On-Prem changes menu

### ISSUE THREAD

**Issue by Gh0stWalk3r** [ostreifel/Pull-Request-Search#7]
Menu of TFS On-Prem installation changes to wrong repository type while viewing the extension/hub.
The extension/hub changes the menu from
![image](https://cloud.githubusercontent.com/assets/10714600/22511491/28fae6ca-e896-11e6-93f2-95b77e48bea5.png)
to
![image](https://cloud.githubusercontent.com/assets/10714600/22511531/4275379a-e896-11e6-94c5-312122ee1118.png)
I think the extension/hub switches from "Git-Menu" to "TFVC-Menu".
Note: Installed TFS version is 2015 U2 and extension version is 1.9.8

**Comment by wfoster232** [comment]
We also have this issue, with the URLs being used to link to PRs also being incorrect.

**Comment by rstedman** [comment]
I had the same issue with a plugin I wrote for tfs.  I confirmed with MS support that it's a bug in earlier versions of tfs/vsts for code hub extensions.  The only fix for this is to upgrade TFS to a newer release.

**Comment by Gh0stWalk3r** [comment]
Ok, I will close this because it is now outdated.
Thanks @rstedman for sharing.
