### ISSUE TITLE
Link to Pull Request doesn't work (On Prem)

### ISSUE THREAD

**Issue by baileyjs78** [ostreifel/Pull-Request-Search#9]
I am using TFS On Prem
The link that is generated, to view the Pull Request, is
http://xxxx:8080/tfs/NS/_git/AppDev/pullrequest/615
Where "NS" is our collection, and "AppDev" is our Team Project
However the link should be
http://xxxx:8080/tfs/NS/AppDev/Apollo/_git/BuyersControlCenter/pullrequest/615
or
http://xxxx:8080/tfs/NS/AppDev/_git/BuyersControlCenter/pullrequest/615
"Apollo" is our Team name and "BuyersControlCenter" is our Repository Name

It is the missing Repository that causes the problem
Attached is the error I receive from TFS
![tfserror](https://cloud.githubusercontent.com/assets/26547339/24105234/9a47bf90-0d5a-11e7-8988-3058330e371a.JPG)

**Comment by ostreifel** [comment]
Which versions of the extension and tfs are you using? This would seem to be a dup of #6 except that #6 was patched awhile back.

**Comment by baileyjs78** [comment]
I just downloaded yesterday, 
1.13.1

**Comment by ostreifel** [comment]
What version is TFS are you using?

**Comment by baileyjs78** [comment]
2017

**Comment by ostreifel** [comment]
Should be fixed now. v1.13.3
